###Create PV with 1GB storage
kind: PersistentVolume
apiVersion: v1
metadata:
  name: kibana-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/kibana"